Repository iTwin/iTwinUI, pull requests merged in 2021-05, with the labels that each got.

#37 Fix tile text blurring on hover
  src/tile/tile.scss
Labels: workaround

#51 Add column filter component
  backstop/results/bitmaps_reference/iTwinUI_column-filter_Type_Date_filter_0_demo-date_0_desktop.png
  backstop/results/bitmaps_reference/iTwinUI_column-filter_Type_Text_filter_0_demo-text_0_desktop.png
  backstop/results/bitmaps_reference/iTwinUI_dark_column-filter_Type_Date_filter_0_demo-date_0_desktop.png
  backstop/results/bitmaps_reference/iTwinUI_dark_column-filter_Type_Text_filter_0_demo-text_0_desktop.png
  backstop/results/bitmaps_reference/iTwinUI_dark_text-area_inline_0_demo-inline_0_desktop.png
  backstop/results/bitmaps_reference/iTwinUI_dark_text-field_basic_0_html_0_desktop.png
  backstop/results/bitmaps_reference/iTwinUI_text-area_inline_0_demo-inline_0_desktop.png
  backstop/results/bitmaps_reference/iTwinUI_text-field_basic_0_html_0_desktop.png
  backstop/scenarios/column-filter.js
  backstop/tests/column-filter.html
  backstop/tests/select.html
  backstop/tests/text-field.html
  src/inputs/classes.scss
  src/inputs/labeled-inputs.scss
  src/menu/classes.scss
  src/menu/menu.scss
  src/table/classes.scss
  src/table/column-filter.scss
  src/table/index.scss
Labels: enhancement

#54 Update file upload component
  backstop/results/bitmaps_reference/iTwinUI_dark_file-upload_Type_not_wrapping_anything_0_demo-no-wrap_0_desktop.png
  backstop/results/bitmaps_reference/iTwinUI_dark_file-upload_Type_table_0_demo-table_0_desktop.png
  backstop/results/bitmaps_reference/iTwinUI_file-upload_Type_not_wrapping_anything_0_demo-no-wrap_0_desktop.png
  backstop/results/bitmaps_reference/iTwinUI_file-upload_Type_table_0_demo-table_0_desktop.png
  backstop/tests/file-upload.html
  src/file-upload/file-upload.scss
Labels: enhancement

#58 Bump hosted-git-info
  package.json
  yarn.lock
Labels: maintenance

#111 Declare $fallback before using it
  src/style/theme.scss
Labels: maintenance

#112 Bump browserslist to 4.16.6
  yarn.lock
Labels: dependencies

#110 Update build.yml to host demo pages
  .github/workflows/build.yml
  backstop/tests/index.html
Labels: maintenance

#121 Updated vulnerable ws package
  yarn.lock
Labels: dependencies
