Repository iTwin/iTwinUI, pull requests merged in 2023-01, with the labels that each got.

#954 chore(Table): Add expanded state to `Table -> ControlledState` story
  apps/storybook/cypress-visual-screenshots/baseline/Table.test.ts-Controlled State.png
  apps/storybook/src/Table.stories.tsx
Labels: documentation

#992 website: Add feedback link
  apps/website/src/components/EditPageLink.astro
  apps/website/src/components/FeedbackLink.astro
  apps/website/src/icons/ChatIcon.astro
  apps/website/src/pages/docs/_layout.astro
Labels: documentation

#956 website: Update badges documentation & demos
  apps/website/src/examples/Badge.soft.tsx
  apps/website/src/examples/Badge.statuses.tsx
  apps/website/src/pages/docs/badge.mdx
Labels: documentation

#1008 `Table -> ControlledState` story without passing `useControlledState`
  apps/storybook/src/Table.stories.tsx
Labels: documentation

#860 feat(Tabs): Right aligned content within Tabs row
  .changeset/cool-baboons-crash.md
  apps/storybook/cypress-visual-screenshots/baseline/Tabs.test.ts-Borderless Tabs.png
  packages/itwinui-css/backstop/results/bitmaps_reference/iTwinUI_tabs_State_hover__focus_in_borderless_dark_0_demo-borderless-2_0_.png
  packages/itwinui-css/backstop/results/bitmaps_reference/iTwinUI_tabs_State_hover__focus_in_borderless_hc_dark_0_demo-borderless-2_0_.png
  packages/itwinui-css/backstop/results/bitmaps_reference/iTwinUI_tabs_State_hover__focus_in_borderless_hc_light_0_demo-borderless-2_0_.png
  packages/itwinui-css/backstop/results/bitmaps_reference/iTwinUI_tabs_State_hover__focus_in_borderless_light_0_demo-borderless-2_0_.png
  packages/itwinui-css/backstop/results/bitmaps_reference/iTwinUI_tabs_State_hover__focus_in_default_dark_0_demo-default-2_0_.png
  packages/itwinui-css/backstop/results/bitmaps_reference/iTwinUI_tabs_State_hover__focus_in_default_hc_dark_0_demo-default-2_0_.png
  packages/itwinui-css/backstop/results/bitmaps_reference/iTwinUI_tabs_State_hover__focus_in_default_hc_light_0_demo-default-2_0_.png
  packages/itwinui-css/backstop/results/bitmaps_reference/iTwinUI_tabs_State_hover__focus_in_default_light_0_demo-default-2_0_.png
  packages/itwinui-css/backstop/results/bitmaps_reference/iTwinUI_tabs_Type_borderless_dark_0_demo-borderless_0_.png
  packages/itwinui-css/backstop/results/bitmaps_reference/iTwinUI_tabs_Type_borderless_hc_dark_0_demo-borderless_0_.png
  packages/itwinui-css/backstop/results/bitmaps_reference/iTwinUI_tabs_Type_borderless_hc_light_0_demo-borderless_0_.png
  packages/itwinui-css/backstop/results/bitmaps_reference/iTwinUI_tabs_Type_borderless_light_0_demo-borderless_0_.png
  packages/itwinui-css/backstop/results/bitmaps_reference/iTwinUI_tabs_Type_borderless_vertical_dark_0_demo-borderless-vertical_0_.png
  packages/itwinui-css/backstop/results/bitmaps_reference/iTwinUI_tabs_Type_borderless_vertical_hc_dark_0_demo-borderless-vertical_0_.png
  packages/itwinui-css/backstop/results/bitmaps_reference/iTwinUI_tabs_Type_borderless_vertical_hc_light_0_demo-borderless-vertical_0_.png
  packages/itwinui-css/backstop/results/bitmaps_reference/iTwinUI_tabs_Type_borderless_vertical_light_0_demo-borderless-vertical_0_.png
  packages/itwinui-css/backstop/results/bitmaps_reference/iTwinUI_tabs_Type_default_dark_0_demo-default_0_.png
  packages/itwinui-css/backstop/results/bitmaps_reference/iTwinUI_tabs_Type_default_hc_dark_0_demo-default_0_.png
  packages/itwinui-css/backstop/results/bitmaps_reference/iTwinUI_tabs_Type_default_hc_light_0_demo-default_0_.png
  packages/itwinui-css/backstop/results/bitmaps_reference/iTwinUI_tabs_Type_default_light_0_demo-default_0_.png
  packages/itwinui-css/backstop/results/bitmaps_reference/iTwinUI_tabs_Type_default_vertical_dark_0_demo-default-vertical_0_.png
  packages/itwinui-css/backstop/results/bitmaps_reference/iTwinUI_tabs_Type_default_vertical_hc_dark_0_demo-default-vertical_0_.png
  packages/itwinui-css/backstop/results/bitmaps_reference/iTwinUI_tabs_Type_default_vertical_hc_light_0_demo-default-vertical_0_.png
  packages/itwinui-css/backstop/results/bitmaps_reference/iTwinUI_tabs_Type_default_vertical_light_0_demo-default-vertical_0_.png
  packages/itwinui-css/backstop/tests/tabs.html
  packages/itwinui-css/src/tabs/classes.scss
  packages/itwinui-css/src/tabs/tabs.scss
Labels: enhancement, css

#1002 feat(Tabs): Right aligned content within Tabs row (React)
  .changeset/chilly-ladybugs-tap.md
  apps/storybook/cypress-visual-screenshots/baseline/Tabs.test.ts-Borderless Tabs.png
  apps/storybook/cypress-visual-screenshots/baseline/Tabs.test.ts-Default Tabs.png
  apps/storybook/cypress-visual-screenshots/baseline/Tabs.test.ts-Sublabels And Icons.png
  apps/storybook/cypress-visual-screenshots/baseline/Tabs.test.ts-Vertical.png
  apps/storybook/src/Tabs.stories.tsx
  packages/itwinui-react/src/core/Tabs/Tabs.tsx
Labels: enhancement, react

#1032 move-on-visible transition in docs website
  apps/website/src/components/utils/MoveOnVisible.astro
  apps/website/src/pages/_global.astro
  apps/website/src/pages/index.astro
Labels: documentation

#997 website: Update dialog documentation & demos
  apps/website/src/demos/Dialog.demo.tsx
  apps/website/src/examples/Dialog.dismissible.tsx
  apps/website/src/examples/Dialog.draggable.tsx
  apps/website/src/examples/Dialog.fullpage.tsx
  apps/website/src/examples/Dialog.main.tsx
  apps/website/src/examples/Dialog.modal.tsx
  apps/website/src/examples/Dialog.nondismissible.tsx
  apps/website/src/examples/Dialog.static.tsx
  apps/website/src/pages/docs/dialog.mdx
Labels: documentation
